BayesOpt: bayesopt::DiscreteModel Class Reference
bayesopt::DiscreteModel Class Reference
BayesOpt
Bayesian optimization for functions in discrete spaces.
#include <bayesopt.hpp>
Public Member Functions
DiscreteModel (const vecOfvec &validSet, bopt_params params)
Constructor for real-valued discrete data.
DiscreteModel (const vectori &categories, bopt_params params)
Constructor for categorical data.
virtual ~DiscreteModel ()
Default destructor.
vectord getFinalResult ()
Once the optimization has been perfomed, return the optimal point.
Public Member Functions inherited from bayesopt::BayesOptBase
BayesOptBase (size_t dim, bopt_params params)
Constructor.
virtual ~BayesOptBase ()
Default destructor.
virtual double evaluateSample (const vectord &query)=0
Function that defines the actual function to be optimized.
virtual bool checkReachability (const vectord &query)
This function checks if the query is valid or not.
void optimize (vectord &bestPoint)
Execute the optimization process of the function defined in evaluateSample.
void stepOptimization ()
Execute ONE step the optimization process of the function defined in evaluateSample.
void initializeOptimization ()
Initialize the optimization process.
ProbabilityDistribution * getPrediction (const vectord &query)
const Dataset * getData ()
bopt_params * getParameters ()
double getValueAtMinimum ()
double evaluateCriteria (const vectord &query)
Protected Member Functions
void plotStepData (size_t iteration, const vectord &xNext, double yNext)
Print data for every step according to the verbose level.
void sampleInitialPoints (matrixd &xPoints, vectord &yPoints)
Selects the initial set of points to build the surrogate model.
vectord samplePoint ()
Sample a single point in the input space.
double evaluateSampleInternal (const vectord &query)
Wrapper for the target function adding any preprocessing or constraint.
void findOptimal (vectord &xOpt)
Returns the optimal point acording to certain criteria.
Protected Member Functions inherited from bayesopt::BayesOptBase
vectord getPointAtMinimum ()
Private Member Functions
DiscreteModel ()
Default constructor forbidden.
Private Attributes
vecOfvec mInputSet
List of input points.
Additional Inherited Members
Protected Attributes inherited from bayesopt::BayesOptBase
bopt_params mParameters
Configuration parameters.
size_t mDims
Number of dimensions.
size_t mCurrentIter
Current iteration number.
boost::mt19937 mEngine
Random number generator.
Detailed Description
Bayesian optimization for functions in discrete spaces.
The discrete space can be created in two ways depending on the constructor used:
A set of discrete points (real vectors) in a real space.
A set of categories with different values for each category.
The kind of models used in this library are more suitable for problems of the first point. However, it can also be used with problems in the second category. In that case, we recommend to use the Hamming kernel function.
Usage:
DiscreteModel opt(validSetOfPoints,params);
\\ or
DiscreteModel opt(categories,params);
Optimization can be run in batch mode calling
opt.optimize(result);
or step by step.
opt.initiliazeOptimization();
\\...
opt.stepOptimization();
\\...
result getFinalResult();
See also
BayesOptBase about how to run the optimization
HammingKernel for categorical data.
Definition at line 180 of file bayesopt.hpp.
Constructor & Destructor Documentation
bayesopt::DiscreteModel::DiscreteModel (const vecOfvec & validSet, bopt_params params)
Constructor for real-valued discrete data.
Parameters
validSet Set of potential inputs
params set of parameters (see parameters.h)
Definition at line 40 of file bayesoptdisc.cpp.
References bayesopt::BayesOptBase::mDims, and mInputSet.
bayesopt::DiscreteModel::DiscreteModel (const vectori & categories, bopt_params params)
Constructor for categorical data.
Parameters
number of categories per dimension
params set of parameters (see parameters.h)
Definition at line 47 of file bayesoptdisc.cpp.
References bayesopt::BayesOptBase::mDims, and mInputSet.
Member Function Documentation
double bayesopt::DiscreteModel::evaluateSampleInternal (const vectord & query) protected virtual
Wrapper for the target function adding any preprocessing or constraint.
Implements bayesopt::BayesOptBase.
Definition at line 71 of file bayesoptdisc.cpp.
References bayesopt::BayesOptBase::evaluateSample().
void bayesopt::DiscreteModel::findOptimal (vectord & xOpt) protected virtual
Returns the optimal point acording to certain criteria.
See also
evaluateCriteria
Parameters
xOpt optimal point
Implements bayesopt::BayesOptBase.
Definition at line 118 of file bayesoptdisc.cpp.
References mInputSet.
vectord bayesopt::DiscreteModel::getFinalResult () virtual
Once the optimization has been perfomed, return the optimal point.
Implements bayesopt::BayesOptBase.
Definition at line 60 of file bayesoptdisc.cpp.
void bayesopt::DiscreteModel::sampleInitialPoints (matrixd & xPoints, vectord & yPoints) protected virtual
Selects the initial set of points to build the surrogate model.
Implements bayesopt::BayesOptBase.
Definition at line 99 of file bayesoptdisc.cpp.
References bayesopt::BayesOptBase::evaluateSample(), bayesopt::BayesOptBase::mEngine, mInputSet, and bayesopt::utils::randomPerms().
vectord bayesopt::DiscreteModel::samplePoint () protected virtual
Sample a single point in the input space.
Used for epsilon greedy exploration.
Implements bayesopt::BayesOptBase.
Definition at line 65 of file bayesoptdisc.cpp.
References bayesopt::BayesOptBase::mEngine, and mInputSet.
The documentation for this class was generated from the following files:
bayesopt.hpp
bayesoptdisc.cpp