BayesOpt: bayesopt::KernelModel Class Reference
bayesopt::KernelModel Class Reference
KernelFunctions
Public Member Functions
KernelModel (size_t dim, bopt_params parameters)
Kernel * getKernel ()
void setHyperParameters (const vectord &theta)
vectord getHyperParameters ()
size_t nHyperParameters ()
void setKernel (const vectord &thetav, const vectord &stheta, std::string k_name, size_t dim)
Select kernel (covariance function) for the surrogate process.
void setKernel (kernel_parameters kernel, size_t dim)
Wrapper of setKernel for C kernel structure.
void computeCorrMatrix (const vecOfvec &XX, matrixd &corrMatrix, double nugget)
void computeDerivativeCorrMatrix (const vecOfvec &XX, matrixd &corrMatrix, int dth_index)
vectord computeCrossCorrelation (const vecOfvec &XX, const vectord &query)
void computeCrossCorrelation (const vecOfvec &XX, const vectord &query, vectord &knx)
double computeSelfCorrelation (const vectord &query)
double kernelLogPrior ()
Private Member Functions
void setKernelPrior (const vectord &theta, const vectord &s_theta)
Set prior (Gaussian) for kernel hyperparameters.
Private Attributes
boost::scoped_ptr< Kernel > mKernel
Pointer to kernel function.
std::vector< boost::math::normal > priorKernel
Prior of kernel parameters.
Detailed Description
Definition at line 90 of file kernel_functors.hpp.
Member Function Documentation
void bayesopt::KernelModel::setKernel (const vectord & thetav, const vectord & stheta, std::string k_name, size_t dim)
Select kernel (covariance function) for the surrogate process.
Parameters
thetav kernel parameters (mean)
stheta kernel parameters (std)
k_name kernel name
Definition at line 118 of file kernel_functors.cpp.
References bayesopt::KernelFactory::create(), mKernel, and setKernelPrior().
Referenced by setKernel().
The documentation for this class was generated from the following files:
kernel_functors.hpp
kernel_functors.cpp