BayesOpt: bayesopt::ContinuousModel Class Reference
bayesopt::ContinuousModel Class Reference
BayesOpt
Bayesian optimization for functions in continuous input spaces.
#include <bayesopt.hpp>
Public Member Functions
ContinuousModel (size_t dim, bopt_params params)
Constructor.
virtual ~ContinuousModel ()
Default destructor.
vectord getFinalResult ()
Once the optimization has been perfomed, return the optimal point.
void setBoundingBox (const vectord &lowerBound, const vectord &upperBound)
Sets the bounding box.
Public Member Functions inherited from bayesopt::BayesOptBase
BayesOptBase (size_t dim, bopt_params params)
Constructor.
virtual ~BayesOptBase ()
Default destructor.
virtual double evaluateSample (const vectord &query)=0
Function that defines the actual function to be optimized.
virtual bool checkReachability (const vectord &query)
This function checks if the query is valid or not.
void optimize (vectord &bestPoint)
Execute the optimization process of the function defined in evaluateSample.
void stepOptimization ()
Execute ONE step the optimization process of the function defined in evaluateSample.
void initializeOptimization ()
Initialize the optimization process.
ProbabilityDistribution * getPrediction (const vectord &query)
const Dataset * getData ()
bopt_params * getParameters ()
double getValueAtMinimum ()
double evaluateCriteria (const vectord &query)
Protected Member Functions
void plotStepData (size_t iteration, const vectord &xNext, double yNext)
Print data for every step according to the verbose level.
void sampleInitialPoints (matrixd &xPoints, vectord &yPoints)
Selects the initial set of points to build the surrogate model.
vectord samplePoint ()
Sample a single point in the input space.
double evaluateSampleInternal (const vectord &query)
Wrapper for the target function adding any preprocessing or constraint.
void findOptimal (vectord &xOpt)
Call the inner optimization method to find the optimal point acording to the criteria.
Protected Member Functions inherited from bayesopt::BayesOptBase
vectord getPointAtMinimum ()
Private Member Functions
ContinuousModel ()
Default constructor forbidden.
Private Attributes
boost::scoped_ptr< utils::BoundingBox< vectord > > mBB
Bounding Box (input space limits)
boost::scoped_ptr< NLOPT_Optimization > cOptimizer
boost::scoped_ptr< CritCallback > mCallback
Additional Inherited Members
Protected Attributes inherited from bayesopt::BayesOptBase
bopt_params mParameters
Configuration parameters.
size_t mDims
Number of dimensions.
size_t mCurrentIter
Current iteration number.
boost::mt19937 mEngine
Random number generator.
Detailed Description
Bayesian optimization for functions in continuous input spaces.
It requires box constrains for the input space. More exactly: .
Usage:
ContinuousModel opt(dim,params);
vectord result(dim), lBound(dim), uBound(dim);
\\.. Define bounds
opt.setBoundingBox(lBound,uBound);
Optimization can be run in batch mode calling
opt.optimize(result);
or step by step.
opt.initiliazeOptimization();
\\...
opt.stepOptimization();
\\...
result getFinalResult();
This model can also be used for discrete/integer data, provided that the callback function provides the corresponding casting or nearest neighbour.
See also
BayesOptBase about how to run the optimization
Definition at line 76 of file bayesopt.hpp.
Constructor & Destructor Documentation
bayesopt::ContinuousModel::ContinuousModel (size_t dim, bopt_params params)
Constructor.
Parameters
dim number of input dimensions
params set of parameters (see parameters.h)
Definition at line 50 of file bayesoptcont.cpp.
References bayesopt::COMBINED, mBB, bayesopt::BayesOptBase::mDims, and bopt_params::n_inner_iterations.
Member Function Documentation
double bayesopt::ContinuousModel::evaluateSampleInternal (const vectord & query) protected virtual
Wrapper for the target function adding any preprocessing or constraint.
It also maps the box constrains to the [0,1] hypercube.
Implements bayesopt::BayesOptBase.
Definition at line 75 of file bayesoptcont.cpp.
References bayesopt::BayesOptBase::evaluateSample(), and mBB.
Referenced by sampleInitialPoints().
void bayesopt::ContinuousModel::findOptimal (vectord & xOpt) protected virtual
Call the inner optimization method to find the optimal point acording to the criteria.
Parameters
xOpt optimal point
Implements bayesopt::BayesOptBase.
Definition at line 86 of file bayesoptcont.cpp.
References bayesopt::BayesOptBase::mEngine.
void bayesopt::ContinuousModel::plotStepData (size_t iteration, const vectord & xNext, double yNext) protected virtual
Print data for every step according to the verbose level.
Parameters
iteration iteration number
xNext next point
yNext function value at next point
Implements bayesopt::BayesOptBase.
Definition at line 144 of file bayesoptcont.cpp.
References mBB, bayesopt::BayesOptBase::mParameters, bopt_params::n_init_samples, bopt_params::n_iterations, and bopt_params::verbose_level.
void bayesopt::ContinuousModel::sampleInitialPoints (matrixd & xPoints, vectord & yPoints) protected virtual
Selects the initial set of points to build the surrogate model.
Implements bayesopt::BayesOptBase.
Definition at line 160 of file bayesoptcont.cpp.
References evaluateSampleInternal(), bopt_params::init_method, bayesopt::BayesOptBase::mEngine, bayesopt::BayesOptBase::mParameters, and bayesopt::utils::samplePoints().
vectord bayesopt::ContinuousModel::samplePoint () protected virtual
Sample a single point in the input space.
Used for epsilon greedy exploration.
Implements bayesopt::BayesOptBase.
Definition at line 116 of file bayesoptcont.cpp.
References bayesopt::BayesOptBase::mDims, and bayesopt::BayesOptBase::mEngine.
void bayesopt::ContinuousModel::setBoundingBox (const vectord & lowerBound, const vectord & upperBound)
Sets the bounding box.
Parameters
lowerBound vector with the lower bounds of the hypercube
upperBound vector with the upper bounds of the hypercube
Definition at line 128 of file bayesoptcont.cpp.
References mBB.
Referenced by bayes_optimization().
The documentation for this class was generated from the following files:
bayesopt.hpp
bayesoptcont.cpp