BayesOpt: bayesopt::BayesOptBase Class Reference
bayesopt::BayesOptBase Class Reference abstract
BayesOpt
Abstract module for Bayesian optimization.
#include <bayesoptbase.hpp>
Public Member Functions
BayesOptBase (size_t dim, bopt_params params)
Constructor.
virtual ~BayesOptBase ()
Default destructor.
virtual double evaluateSample (const vectord &query)=0
Function that defines the actual function to be optimized.
virtual bool checkReachability (const vectord &query)
This function checks if the query is valid or not.
void optimize (vectord &bestPoint)
Execute the optimization process of the function defined in evaluateSample.
void stepOptimization ()
Execute ONE step the optimization process of the function defined in evaluateSample.
void initializeOptimization ()
Initialize the optimization process.
virtual vectord getFinalResult ()=0
Once the optimization has been perfomed, return the optimal point.
ProbabilityDistribution * getPrediction (const vectord &query)
const Dataset * getData ()
bopt_params * getParameters ()
double getValueAtMinimum ()
double evaluateCriteria (const vectord &query)
Protected Member Functions
vectord getPointAtMinimum ()
virtual void plotStepData (size_t iteration, const vectord &xNext, double yNext)=0
Print data for every step according to the verbose level.
virtual double evaluateSampleInternal (const vectord &query)=0
Wrapper for the target function normalize in the hypercube [0,1].
virtual void findOptimal (vectord &xOpt)=0
Returns the optimal point acording to certain criteria.
virtual void sampleInitialPoints (matrixd &xPoints, vectord &yPoints)=0
Selects the initial set of points to build the surrogate model.
virtual vectord samplePoint ()=0
Sample a single point in the input space.
Protected Attributes
bopt_params mParameters
Configuration parameters.
size_t mDims
Number of dimensions.
size_t mCurrentIter
Current iteration number.
boost::mt19937 mEngine
Random number generator.
Private Member Functions
vectord nextPoint ()
Selects the next point to evaluate according to a certain criteria or metacriteria.
Private Attributes
boost::scoped_ptr< PosteriorModel > mModel
double mYPrev
size_t mCounterStuck
Detailed Description
Abstract module for Bayesian optimization.
This module provides Bayesian optimization using different non-parametric processes (Gaussian process or Student's t process) as distributions over surrogate functions.
See also
ContinuousModel for implementations of this module for a continuous input spaces
DiscreteModel for implementations of this module for a discrete input spaces or categorical input variables
Definition at line 65 of file bayesoptbase.hpp.
Constructor & Destructor Documentation
bayesopt::BayesOptBase::BayesOptBase (size_t dim, bopt_params params)
Constructor.
Parameters
params set of parameters (see parameters.h)
Definition at line 34 of file bayesoptbase.cpp.
References bopt_params::log_filename, mEngine, mParameters, bopt_params::n_init_samples, bopt_params::n_iterations, bopt_params::random_seed, and bopt_params::verbose_level.
Member Function Documentation
virtual bool bayesopt::BayesOptBase::checkReachability (const vectord & query) inline virtual
This function checks if the query is valid or not.
It can be used to introduce arbitrary constrains. Since the Gaussian process assumes smoothness, constrains are managed by the inner optimizer (e.g.:DIRECT), being highly time consuming. If the constrain is very tricky, DIRECT will need much more function evaluations.
Note: This function is experimental. Thus it is not made pure virtual. Using it is completely optional.
Parameters
query point to be evaluated.
Returns
boolean value showing if the the function is valid at the query point or not.
Reimplemented in ExampleHartmann6, ExampleCamelback, BraninNormalized, ExampleDisc, ExampleQuadratic, and ExampleOneD.
Definition at line 106 of file bayesoptbase.hpp.
virtual double bayesopt::BayesOptBase::evaluateSample (const vectord & query) pure virtual
Function that defines the actual function to be optimized.
This function must be modified (overriden) according to the specific problem.
Parameters
query point to be evaluated.
Returns
value of the function at the point evaluated.
Implemented in ExampleHartmann6, ExampleCamelback, CDiscreteModel, BraninNormalized, ExampleDisc, ExampleQuadratic, CContinuousModel, and ExampleOneD.
Referenced by bayesopt::ContinuousModel::evaluateSampleInternal(), bayesopt::DiscreteModel::evaluateSampleInternal(), bayesoptmodule.BayesOptContinuous::optimize(), bayesoptmodule.BayesOptDiscrete::optimize(), bayesoptmodule.BayesOptCategorical::optimize(), and bayesopt::DiscreteModel::sampleInitialPoints().
virtual double bayesopt::BayesOptBase::evaluateSampleInternal (const vectord & query) protected pure virtual
Wrapper for the target function normalize in the hypercube [0,1].
Parameters
query point to evaluate in [0,1] hypercube
Returns
actual return value of the target function
Implemented in bayesopt::DiscreteModel, and bayesopt::ContinuousModel.
Referenced by stepOptimization().
virtual void bayesopt::BayesOptBase::findOptimal (vectord & xOpt) protected pure virtual
Returns the optimal point acording to certain criteria.
See also
evaluateCriteria
Parameters
xOpt optimal point
Implemented in bayesopt::DiscreteModel, and bayesopt::ContinuousModel.
Referenced by nextPoint().
virtual vectord bayesopt::BayesOptBase::getFinalResult () pure virtual
Once the optimization has been perfomed, return the optimal point.
Implemented in bayesopt::DiscreteModel, and bayesopt::ContinuousModel.
Referenced by optimize().
void bayesopt::BayesOptBase::initializeOptimization ()
Initialize the optimization process.
Definition at line 123 of file bayesoptbase.cpp.
References mCurrentIter, mDims, mParameters, bopt_params::n_init_samples, sampleInitialPoints(), and bopt_params::verbose_level.
Referenced by optimize().
vectord bayesopt::BayesOptBase::nextPoint () private
Selects the next point to evaluate according to a certain criteria or metacriteria.
Returns
next point to evaluate
Definition at line 160 of file bayesoptbase.cpp.
References bopt_params::epsilon, findOptimal(), mDims, mEngine, mParameters, and samplePoint().
Referenced by stepOptimization().
void bayesopt::BayesOptBase::optimize (vectord & bestPoint)
Execute the optimization process of the function defined in evaluateSample.
See also
evaluateSample
checkReachability
Parameters
bestPoint returns point with the optimum value in a ublas::vector.
Definition at line 147 of file bayesoptbase.cpp.
References getFinalResult(), initializeOptimization(), mDims, mParameters, bopt_params::n_iterations, and stepOptimization().
Referenced by bayes_optimization(), bayes_optimization_categorical(), and bayes_optimization_disc().
virtual void bayesopt::BayesOptBase::plotStepData (size_t iteration, const vectord & xNext, double yNext) protected pure virtual
Print data for every step according to the verbose level.
Parameters
iteration
xNext
yNext
Implemented in bayesopt::DiscreteModel, and bayesopt::ContinuousModel.
Referenced by stepOptimization().
virtual void bayesopt::BayesOptBase::sampleInitialPoints (matrixd & xPoints, vectord & yPoints) protected pure virtual
Selects the initial set of points to build the surrogate model.
Implemented in bayesopt::DiscreteModel, and bayesopt::ContinuousModel.
Referenced by initializeOptimization().
virtual vectord bayesopt::BayesOptBase::samplePoint () protected pure virtual
Sample a single point in the input space.
Used for epsilon greedy exploration.
Implemented in bayesopt::DiscreteModel, and bayesopt::ContinuousModel.
Referenced by nextPoint(), and stepOptimization().
The documentation for this class was generated from the following files:
bayesoptbase.hpp
bayesoptbase.cpp