BayesOpt: ExampleHartmann6 Class Reference
ExampleHartmann6 Class Reference
Public Member Functions
ExampleHartmann6 (bopt_params par)
double evaluateSample (const vectord &xin)
Function that defines the actual function to be optimized.
bool checkReachability (const vectord &query)
This function checks if the query is valid or not.
double sqr (double x)
void printOptimal ()
Public Member Functions inherited from bayesopt::ContinuousModel
ContinuousModel (size_t dim, bopt_params params)
Constructor.
virtual ~ContinuousModel ()
Default destructor.
vectord getFinalResult ()
Once the optimization has been perfomed, return the optimal point.
void setBoundingBox (const vectord &lowerBound, const vectord &upperBound)
Sets the bounding box.
Public Member Functions inherited from bayesopt::BayesOptBase
BayesOptBase (size_t dim, bopt_params params)
Constructor.
virtual ~BayesOptBase ()
Default destructor.
void optimize (vectord &bestPoint)
Execute the optimization process of the function defined in evaluateSample.
void stepOptimization ()
Execute ONE step the optimization process of the function defined in evaluateSample.
void initializeOptimization ()
Initialize the optimization process.
ProbabilityDistribution * getPrediction (const vectord &query)
const Dataset * getData ()
bopt_params * getParameters ()
double getValueAtMinimum ()
double evaluateCriteria (const vectord &query)
Private Attributes
matrixd mA
vectord mC
matrixd mP
Additional Inherited Members
Protected Member Functions inherited from bayesopt::ContinuousModel
void plotStepData (size_t iteration, const vectord &xNext, double yNext)
Print data for every step according to the verbose level.
void sampleInitialPoints (matrixd &xPoints, vectord &yPoints)
Selects the initial set of points to build the surrogate model.
vectord samplePoint ()
Sample a single point in the input space.
double evaluateSampleInternal (const vectord &query)
Wrapper for the target function adding any preprocessing or constraint.
void findOptimal (vectord &xOpt)
Call the inner optimization method to find the optimal point acording to the criteria.
Protected Member Functions inherited from bayesopt::BayesOptBase
vectord getPointAtMinimum ()
Protected Attributes inherited from bayesopt::BayesOptBase
bopt_params mParameters
Configuration parameters.
size_t mDims
Number of dimensions.
size_t mCurrentIter
Current iteration number.
boost::mt19937 mEngine
Random number generator.
Detailed Description
Definition at line 148 of file testfunctions.hpp.
Member Function Documentation
bool ExampleHartmann6::checkReachability (const vectord & query) inline virtual
This function checks if the query is valid or not.
It can be used to introduce arbitrary constrains. Since the Gaussian process assumes smoothness, constrains are managed by the inner optimizer (e.g.:DIRECT), being highly time consuming. If the constrain is very tricky, DIRECT will need much more function evaluations.
Note: This function is experimental. Thus it is not made pure virtual. Using it is completely optional.
Parameters
query point to be evaluated.
Returns
boolean value showing if the the function is valid at the query point or not.
Reimplemented from bayesopt::BayesOptBase.
Definition at line 183 of file testfunctions.hpp.
double ExampleHartmann6::evaluateSample (const vectord & query) inline virtual
Function that defines the actual function to be optimized.
This function must be modified (overriden) according to the specific problem.
Parameters
query point to be evaluated.
Returns
value of the function at the point evaluated.
Implements bayesopt::BayesOptBase.
Definition at line 167 of file testfunctions.hpp.
Referenced by bayesoptmodule.BayesOptContinuous::optimize(), bayesoptmodule.BayesOptDiscrete::optimize(), and bayesoptmodule.BayesOptCategorical::optimize().
The documentation for this class was generated from the following file:
testfunctions.hpp