BayesOpt: BayesOpt
BayesOpt
Main module for Bayesian optimization.
Classes
class bayesopt::ContinuousModel
Bayesian optimization for functions in continuous input spaces.
class bayesopt::DiscreteModel
Bayesian optimization for functions in discrete spaces.
class bayesopt::BayesOptBase
Abstract module for Bayesian optimization.
class bayesopt::EmpiricalBayes
Bayesian optimization using different non-parametric processes as distributions over surrogate functions.
class bayesopt::PosteriorFixed
Bayesian optimization using different non-parametric processes as distributions over surrogate functions.
class bayesopt::PosteriorModel
Bayesian optimization using different non-parametric processes as distributions over surrogate functions.
Typedefs
typedef double(* eval_func) (unsigned int n, const double *x, double *gradient, void *func_data)
Functions
static PosteriorModel * bayesopt::PosteriorModel::create (size_t dim, bopt_params params, randEngine &eng)
bayesopt::PosteriorModel::PosteriorModel (size_t dim, bopt_params params, randEngine &eng)
Constructor.
virtual bayesopt::PosteriorModel::~PosteriorModel ()
Default destructor.
virtual void bayesopt::PosteriorModel::updateHyperParameters ()=0
virtual void bayesopt::PosteriorModel::fitSurrogateModel ()=0
virtual void bayesopt::PosteriorModel::updateSurrogateModel ()=0
virtual double bayesopt::PosteriorModel::evaluateCriteria (const vectord &query)=0
virtual void bayesopt::PosteriorModel::updateCriteria (const vectord &query)=0
virtual bool bayesopt::PosteriorModel::criteriaRequiresComparison ()=0
virtual void bayesopt::PosteriorModel::setFirstCriterium ()=0
virtual bool bayesopt::PosteriorModel::setNextCriterium (const vectord &prevResult)=0
virtual std::string bayesopt::PosteriorModel::getBestCriteria (vectord &best)=0
void bayesopt::PosteriorModel::setSamples (const matrixd &x, const vectord &y)
void bayesopt::PosteriorModel::setSample (const vectord &x, double y)
void bayesopt::PosteriorModel::addSample (const vectord &x, double y)
double bayesopt::PosteriorModel::getValueAtMinimum ()
vectord bayesopt::PosteriorModel::getPointAtMinimum ()
void bayesopt::PosteriorModel::plotDataset (TLogLevel level)
const Dataset * bayesopt::PosteriorModel::getData ()
virtual ProbabilityDistribution * bayesopt::PosteriorModel::getPrediction (const vectord &query)=0
BAYESOPT_API int bayes_optimization (int nDim, eval_func f, void *f_data, const double *lb, const double *ub, double *x, double *minf, bopt_params parameters)
C wrapper for the Bayesian optimization algorithm.
BAYESOPT_API int bayes_optimization_disc (int nDim, eval_func f, void *f_data, double *valid_x, size_t n_points, double *x, double *minf, bopt_params parameters)
C wrapper for the Bayesian optimization algorithm.
BAYESOPT_API int bayes_optimization_categorical (int nDim, eval_func f, void *f_data, int *categories, double *x, double *minf, bopt_params parameters)
C wrapper for the Bayesian optimization algorithm.
Variables
bopt_params bayesopt::PosteriorModel::mParameters
Configuration parameters.
size_t bayesopt::PosteriorModel::mDims
Number of dimensions.
Dataset bayesopt::PosteriorModel::mData
Dataset (x-> inputs, y-> labels/output)
MeanModel bayesopt::PosteriorModel::mMean
Detailed Description
Main module for Bayesian optimization.
Function Documentation
BAYESOPT_API int bayes_optimization (int nDim, eval_func f, void * f_data, const double * lb, const double * ub, double * x, double * minf, bopt_params parameters)
C wrapper for the Bayesian optimization algorithm.
This function assumes continuous optimization.
Parameters
nDim number of input dimensions
f pointer to the function to optimize
f_data pointer to extra data to be used by f
lb array of lower bounds
ub array of upper bounds
x input: initial query, output: result (minimum)
minf value of the function at the minimum
parameters parameters for the Bayesian optimization.
Returns
error code
Definition at line 96 of file bayesoptwpr.cpp.
References bayesopt::BayesOptBase::optimize(), and bayesopt::ContinuousModel::setBoundingBox().
BAYESOPT_API int bayes_optimization_categorical (int nDim, eval_func f, void * f_data, int * categories, double * x, double * minf, bopt_params parameters)
C wrapper for the Bayesian optimization algorithm.
This assumes the input variables are categories. Use of the Hamming kernel is highly recommended.
Parameters
nDim number of input dimensions
f pointer to the function to optimize
f_data pointer to extra data to be used by f
categories number of categories on each dimension
x input: initial query, output: result (minimum)
minf value of the function at the minimum
parameters parameters for the Bayesian optimization.
Returns
error code
Definition at line 201 of file bayesoptwpr.cpp.
References bayesopt::BayesOptBase::optimize().
BAYESOPT_API int bayes_optimization_disc (int nDim, eval_func f, void * f_data, double * valid_x, size_t n_points, double * x, double * minf, bopt_params parameters)
C wrapper for the Bayesian optimization algorithm.
This function assumes discrete optimization.
Parameters
nDim number of input dimensions
f pointer to the function to optimize
f_data pointer to extra data to be used by f
valid_x set of possible discrete points
n_points number of possible discrete points
x input: initial query, output: result (minimum)
minf value of the function at the minimum
parameters parameters for the Bayesian optimization.
Returns
error code
Definition at line 141 of file bayesoptwpr.cpp.
References bopt_params::n_init_samples, bopt_params::n_iterations, and bayesopt::BayesOptBase::optimize().
bayesopt::PosteriorModel::PosteriorModel (size_t dim, bopt_params params, randEngine & eng)
Constructor.
Parameters
params set of parameters (see parameters.h)
Definition at line 46 of file posteriormodel.cpp.